name: hendrics

channels:
    - astropy

dependencies:
    - python=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - pip:
       - git+https://github.com/stingraysoftware/stingray.git
