# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows.
# Copied shamelessly from Astropy

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci_scripts\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

  matrix:

      # We test Python 2.6 and 3.4 because 2.6 is most likely to have issues in
      # Python 2 (if 2.6 passes, 2.7 virtually always passes) and Python 3.4 is
      # the latest Python 3 release.

      - PYTHON_VERSION: "2.7"
        NETCDF_LIB: "netcdf4"
      - PYTHON_VERSION: "3.4"
        NETCDF_LIB: "netcdf4"
      - PYTHON_VERSION: "2.7"
        NETCDF_LIB: ""
      - PYTHON_VERSION: "3.4"
        NETCDF_LIB: ""

platform:
    -x64

install:
    # Install miniconda using a powershell script.
    - "powershell ci_scripts/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build and runtime dependencies of the project.
    - "conda update --yes conda"
    # Create a conda environment using the astropy bonus packages
    - "conda create -q --yes -n test -c astropy-ci-extras python=%PYTHON_VERSION%"
    - "activate test"

    # Check that we have the expected version of Python
    - "python --version"

    # Install specified version of numpy and dependencies
    - "conda install -q --yes scipy %NETCDF_LIB% astropy numpy matplotlib"
    - python setup.py install

# Not a .NET project, we build SunPy in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% python test\\utests.py"
  - "%CMD_IN_ENV% python test\\fullrun.py"
