codecov:
    notify: false
    # do not notify (default notification is email)

comment:
    after_n_builds: 6
    # will leave a comment on the pull request once all 6 coverage-reporting
    # (-cov) jobs of the CI matrix have uploaded their results

coverage:
  round: nearest
  # rounds the coverage percentage to the nearest value,
  # instead of always rounding down (former default behaviour)
