#!/usr/bin/env python
from __future__ import division, print_function
from maltpynt.mp_save_as_xspec import mp_save_as_xspec
import argparse

description = 'Saves a frequency spectrum in a qdp file that can be' + \
    ' read by flx2xsp and produce a XSpec-compatible spectrum file'
parser = argparse.ArgumentParser(description=description)
parser.add_argument("files", help="List of files", nargs='+')
args = parser.parse_args()
fnames = args.files
for f in fnames:
    mp_save_as_xspec(f)
