#!/usr/bin/env python
from __future__ import division, print_function
from maltpynt.mp_save_as_xspec import mp_save_as_xspec
import argparse
import logging

description = ('Save a frequency spectrum in a qdp file that can be '
               'read by flx2xsp and produce a XSpec-compatible spectrum file')
parser = argparse.ArgumentParser(description=description)
parser.add_argument("files", help="List of files", nargs='+')
parser.add_argument("--loglevel",
                    help=("use given logging level (one between INFO, "
                          "WARNING, ERROR, CRITICAL, DEBUG; default:WARNING)"),
                    default='WARNING',
                    type=str)
parser.add_argument("--debug", help="use DEBUG logging level",
                    default=False, action='store_true')
args = parser.parse_args()
files = args.files
if args.debug:
    args.loglevel = 'DEBUG'

numeric_level = getattr(logging, args.loglevel.upper(), None)
logging.basicConfig(filename='MP2xpec.log', level=numeric_level,
                    filemode='w')

for f in files:
    mp_save_as_xspec(f)
