#!/usr/bin/env python
from __future__ import division, print_function
import sys
from maltpynt.mp_io import mp_get_file_type

from maltpynt.mp_plot import mp_plot_lc, mp_plot_cospectrum, mp_plot_pds


for fname in sys.argv[1:]:
    ftype, contents = mp_get_file_type(fname)
    if ftype == 'lc':
        mp_plot_lc(fname)
    elif ftype[-4:] == 'cpds':
        mp_plot_cospectrum(fname)
    elif ftype[-3:] == 'pds':
        mp_plot_pds(fname)
