#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst

from __future__ import (absolute_import, unicode_literals, division,
                        print_function)

import matplotlib.pyplot as plt
from maltpynt.mp_io import mp_get_file_type
from maltpynt.mp_plot import mp_plot_lc, mp_plot_cospectrum, mp_plot_pds
import argparse

description = \
    'Plot the content of MaLTPyNT light curves and frequency spectra'
parser = argparse.ArgumentParser(description=description)
parser.add_argument("files", help="List of files", nargs='+')

if __name__ == '__main__':
    import sys
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)
    args = parser.parse_args()
    for fname in args.files:
        ftype, contents = mp_get_file_type(fname)
        if ftype == 'lc':
            mp_plot_lc(fname)
        elif ftype[-4:] == 'cpds':
            mp_plot_cospectrum(fname)
        elif ftype[-3:] == 'pds':
            mp_plot_pds(fname)

    plt.show()
