#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst

from __future__ import (absolute_import, unicode_literals, division,
                        print_function)

import sys
from maltpynt.mp_io import mp_get_file_type, is_string
import collections


def usage():
    print('''Usage:

          mpreadfile filename

          where filename is any file in a valid MaLTPyNT format
          ''')

try:
    fname = sys.argv[1]
except:
    usage()
    sys.exit()

ftype, contents = mp_get_file_type(fname)
print('-----------------------------')
print('This file contains:', end='\n\n')
for k in sorted(contents.keys()):
    val = contents[k]
    if isinstance(val, collections.Iterable) and not is_string(val):
        if len(val) < 4:
            val = repr(list(val[:4]))
        else:
            val = repr(list(val[:4])).replace(']', '') + '...]'
    print((k + ':').ljust(15), val, end='\n\n')

print('-----------------------------')
