#!/usr/bin/env python
from __future__ import division, print_function
from maltpynt.mp_rebin import mp_rebin_file
import argparse

description = 'Rebins light curves and frequency spectra. '
parser = argparse.ArgumentParser(description=description)

parser.add_argument("files", help="List of light curve files", nargs='+')
parser.add_argument("-r", "--rebin", type=float, default=1,
                    help="Rebinning to apply. Only if the quantity to" +
                    " rebin is a (C)PDS, it is possible to specify a" +
                    " non-integer rebin factor, in which case it is" +
                    " interpreted as a geometrical binning factor")

args = parser.parse_args()

rebin = args.rebin
for f in args.files:
    mp_rebin_file(f, rebin)
