#!/usr/bin/env python
"""Sum a bunch of (c)PDSs contained in a list of files."""
# Licensed under a 3-clause BSD style license - see LICENSE.rst

from __future__ import (absolute_import, unicode_literals, division,
                        print_function)

from maltpynt.mp_sum_fspec import sum_fspec
from maltpynt.mp_io import MP_FILE_EXTENSION
import argparse

if __name__ == '__main__':
    description = 'Sum (C)PDSs contained in different files'
    parser = argparse.ArgumentParser(description=description)

    parser.add_argument("files", help="List of light curve files", nargs='+')

    parser.add_argument("-o", "--outname", type=str, default=None,
                        help='Output file name for summed (C)PDS. Default:' +
                        ' tot_(c)pds' + MP_FILE_EXTENSION)

    args = parser.parse_args()

    sum_fspec(args.files, args.outname)
