# Licensed under a 3-clause BSD style license - see LICENSE.rst
#
# Astropy documentation build configuration file.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this file.
#
# All configuration values have a default. Some values are defined in
# the global Astropy configuration which is loaded here before anything else.
# See astropy.sphinx.conf for which values are set there.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('..'))
# IMPORTANT: the above commented section was generated by sphinx-quickstart, but
# is *NOT* appropriate for astropy or Astropy affiliated packages. It is left
# commented out with this explanation to make it clear why this should not be
# done. If the sys.path entry above is added, when the astropy.sphinx.conf
# import occurs, it will import the *source* version of astropy instead of the
# version installed (if invoked as "make html" or directly with sphinx), or the
# version in the build directory (if "python setup.py build_sphinx" is used).
# Thus, any C-extensions that are needed to build the documentation will *not*
# be accessible, and the documentation will not build correctly.

import datetime
import os
import subprocess as sp
import sys
import sysconfig
import warnings
from importlib import import_module

from docutils import nodes
from docutils.parsers.rst import roles

try:
    from sphinx_astropy.conf.v1 import *  # noqa
except ImportError:
    print("ERROR: the documentation requires the sphinx-astropy package to be installed")
    sys.exit(1)
try:
    import tomllib
except ImportError:
    # Help users on older alphas
    import tomli as tomllib
from pathlib import Path

warnings.filterwarnings("ignore", message=".*recommended numba.*")
warnings.filterwarnings("ignore", message=".*Using pickle.*")
warnings.filterwarnings("ignore", message=".*PINT is not installed.*")

# Grab minversion from pyproject.toml
with (Path(__file__).parents[1] / "pyproject.toml").open("rb") as f:
    pyproject = tomllib.load(f)


# -- General configuration ----------------------------------------------------

# By default, highlight as Python 3.
# highlight_language = 'python3'

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.2'

# To perform a Sphinx version check that needs to be more specific than
# major.minor, call `check_sphinx_version("x.y.z")` here.
# check_sphinx_version("1.2.1")

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns.append("_templates")
exclude_patterns.append("changes")

# This is added to the end of RST files - a good place to put substitutions to
# be used globally.
rst_epilog += """
"""


# ``SliderOnSteroids`` inherits its documentation from ``matplotlib.widgets.
# Slider``, which is written with matplotlib's own ``:mpltype:`` role. Sphinx
# knows nothing about it here, so register a version that renders as literal
# text rather than raising an error on the page.
def mpltype_role(name, rawtext, text, lineno, inliner, options=None, content=None):
    return [nodes.literal(rawtext, text)], []


roles.register_local_role("mpltype", mpltype_role)

# -- Project information ------------------------------------------------------

# This does not *have* to match the package name, but typically does
project = pyproject["project"]["name"]
author = ", ".join(a["name"] for a in pyproject["project"]["authors"])
copyright = f"{datetime.datetime.now().year}, {author}"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

import_module(pyproject["project"]["name"])
package = sys.modules[pyproject["project"]["name"]]

# The short X.Y version.
version = package.__version__.split("-", 1)[0]
# The full version, including alpha/beta/rc tags.
release = package.__version__


# -- Options for HTML output --------------------------------------------------

# A NOTE ON HTML THEMES
# The global astropy configuration uses a custom theme, 'bootstrap-astropy',
# which is installed along with astropy. A different theme can be used or
# the options for this theme can be modified by overriding some of the
# variables set in the global configuration. The variables set in the
# global configuration are listed below, commented out.


# Add any paths that contain custom themes here, relative to this directory.
# To use a different custom theme, add the directory containing the theme.
# html_theme_path = ['themes']

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes. To override the custom theme, set this to the
# name of a builtin theme or the name of a custom theme in html_theme_path.
# html_theme = None


html_theme_options = {
    "logotext1": "HENDR",  # white,  semi-bold
    "logotext2": "ICS",  # orange, light
    "logotext3": ":docs",  # white,  light
}


# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "images/hendrics_logo.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "images/hendrics_logo_32.png"

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
# html_last_updated_fmt = ''

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = f"{project} v{release}"

# Output file base name for HTML help builder.
htmlhelp_basename = project + "doc"


# -- Options for LaTeX output -------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [("index", project + ".tex", project + " Documentation", author, "manual")]


# -- Options for manual page output -------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [("index", project.lower(), project + " Documentation", [author], 1)]


extensions += ["sphinx_toolbox.collapse"]
# -- Options for the edit_on_github extension ---------------------------------

# Trust the links from these sites, even if they might have Client errors or other minor issues
linkcheck_ignore = [
    r"https://doi.org/",
    r"https://arxiv.org/",
    r"https://.*adsabs.harvard.edu/",
    r"https://zenodo.org/",
    r"http.*://stackoverflow.com/questions/.*",
    r"https://.*.nasa.gov/.*",
    # The server omits its intermediate certificate, so Python cannot verify it
    r"https://ascl.net/",
    # Bot protection redirects automated requests to a challenge page
    r"https://iopscience.iop.org/",
]

# -- Options for the edit_on_github extension ---------------------------------

edit_on_github_branch = "main"

# -- Resolving issue number to links in changelog -----------------------------
github_issues_url = pyproject["project"]["urls"]["repository"] + "/issues/"

# -- Turn on nitpicky mode for sphinx (to warn about references not found) ----
#
# nitpicky = True
# nitpick_ignore = []
#
# Some warnings are impossible to suppress, and you can list specific references
# that should be ignored in a nitpick-exceptions file which should be inside
# the docs/ directory. The format of the file should be:
#
# <type> <class>
#
# for example:
#
# py:class astropy.io.votable.tree.Element
# py:class astropy.io.votable.tree.SimpleElement
# py:class astropy.io.votable.tree.SimpleElementWithContent
#
# Uncomment the following lines to enable the exceptions:
#
# for line in open('nitpick-exceptions'):
#     if line.strip() == "" or line.startswith("#"):
#         continue
#     dtype, target = line.split(None, 1)
#     target = target.strip()
#     nitpick_ignore.append((dtype, six.u(target)))

# Regenerate the command line reference from the installed scripts. This used
# to be skipped on Read the Docs, so the site everybody reads served whatever
# stale copy happened to be committed.
scripts = pyproject["project"]["scripts"]
pwarn = os.getenv("PYTHONWARNINGS")

os.environ["PYTHONWARNINGS"] = "ignore"
cols = os.getenv("COLUMNS")
os.environ["COLUMNS"] = "80"

cli_file = Path(__file__).parent / "scripts" / "cli.rst"
cli_file.parent.mkdir(parents=True, exist_ok=True)
with cli_file.open("w") as fobj:
    print("""Command line interface""", file=fobj)
    print("""======================\n""", file=fobj)

    for cl in sorted(scripts.keys()):
        print(f"Writing help for {cl}")
        # Calling the scripts by bare name would go through PATH, where a
        # different HENDRICS installation can easily shadow this one.
        command = os.path.join(sysconfig.get_path("scripts"), cl)
        print(cl, file=fobj)
        print("-" * len(cl), file=fobj)
        print(file=fobj)
        print("::", file=fobj)
        print(file=fobj)
        lines = sp.check_output([command, "--help"]).decode().split("\n")
        for line in lines:
            if line.strip() == "":
                print(file=fobj)
            else:
                print("    " + line, file=fobj)
        print(file=fobj)

if cols is not None:
    os.environ["COLUMNS"] = cols
else:
    del os.environ["COLUMNS"]

if pwarn is not None:
    os.environ["PYTHONWARNINGS"] = pwarn
else:
    del os.environ["PYTHONWARNINGS"]
