name: hendrics

channels:
  - conda-forge

dependencies:
  - python==3.5
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - pip:
    - nbsphinx
    - stingray >= 0.1rc1
